CREATE VIEW IF NOT EXISTS "RELATED_RECOMMENDATIONS" AS
    SELECT
        VIDEOS_RAW._id as _id,
        VIDEOS_RAW.REF_ID,
        VIDEOS_RAW.LANGUAGE_ID,
        VIDEOS_RAW.STREAM_ID,
        VIDEOS_RAW.PROGRAM_ID,
        VIDEOS_RAW.TYPE,
        VIDEOS_RAW.TITLE,
        VIDEOS_RAW.TEXT,
        VIDEOS_RAW.SUBTITLE,
        VIDEOS_RAW.DURATION,
        VIDEOS_RAW.THUMBNAIL_URL,
        VIDEOS_RAW.POSITION,
        VIDEOS_RAW.DATE,
        VIDEOS_RAW.RIGHTS_AFTER,
        VIDEOS_RAW.RIGHTS_UNTIL,
        VIDEOS_RAW.ADULT,
        VIDEOS_RAW.WARNING,
        VIDEOS_RAW.VIDEO_VIEWS,
        VIDEOS_RAW.RATING,
        VIDEOS_RAW.RECOMMENDED,
        VIDEOS_RAW.PLUS7_TEASER,
        VIDEOS_RAW.RANK,
        VIDEOS_RAW.GEO_BLOCKING,
        VIDEOS_RAW.GEO_BLOCKING_ORD,
        VIDEOS_RAW.ISO_LANG,
        VIDEOS_RAW.WATCH_POSITION,
        PROGRAMS.TITLE AS PROGRAM_TITLE,
        PROGRAMS.GENRE_ID AS GENRE_ID,
        VIDEO_CHANNEL.CHANNEL_ID,
        BROADCASTS.MAIN_CLUSTER_ID AS CLUSTER_ID
    FROM VIDEOS_RAW
    OUTER LEFT JOIN PROGRAMS
        ON VIDEOS_RAW.PROGRAM_ID = PROGRAMS.PROGRAM_ID
            AND VIDEOS_RAW.LANGUAGE_ID = PROGRAMS.LANGUAGE_ID
    OUTER LEFT JOIN VIDEO_CHANNEL
        ON VIDEOS_RAW.REF_ID = VIDEO_CHANNEL.VIDEO_ID
    OUTER LEFT JOIN BROADCASTS
        ON BROADCASTS.PROGRAM_ID = PROGRAMS.PROGRAM_ID
            AND PROGRAMS.LANGUAGE_ID = BROADCASTS.LANGUAGE_ID
    GROUP BY VIDEOS_RAW.REF_ID;
