# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command
# To edit any of the Enviroment variables please do so from the .env files

default_platform(:ios)

platform :ios do

  ######################### RELEASE #########################

  desc "Deploy a new version to the iTunes Connect"
  lane :release_build do
    ensure_git_status_clean
    build_number = get_build_number(xcodeproj: ENV["PROJECT"])
    version_number = get_version_number(xcodeproj: ENV["PROJECT"])
    gym
    slack
  end

  desc "Run tests and SwiftLint"
  lane :verify_app do
    scan
  end
end
